const FILE_TYPES = ["png", "jpg", "jpeg"]
const PROFILE_FILEPREFIX = "profile_pic_url"
const PROFILE_FIELDNAME = "profilePicUrl"
const PROPERTY_FILEPREFIX = "property_pic_url"
const PROPERTY_FIELDNAME = "propertyPicUrl"
const ROOM_FILEPREFIX = "room_pic_url"
const ROOM_FIELDNAME = "roomPicUrl"
const PAYMENTPROOF_FILLEPREFIX = "payment_proof_url"
const PAYMENTPROOF_FIELDNAME = "paymentUrl"

const LIMIT_FILE_SIZE = "LIMIT_FILE_SIZE"

const SIZE_2MB = 2 * 1024 * 1024
const SIZE_1MB = 1 * 1024 * 1024

module.exports = {
  PROFILE_FIELDNAME,
  PROFILE_FILEPREFIX,
  FILE_TYPES,
  LIMIT_FILE_SIZE,
  PROPERTY_FILEPREFIX,
  PROPERTY_FIELDNAME,
  ROOM_FIELDNAME,
  ROOM_FILEPREFIX,
  SIZE_2MB,
  PAYMENTPROOF_FIELDNAME,
  PAYMENTPROOF_FILLEPREFIX,
  SIZE_1MB,
}
